spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Ativa a execução de scripts SQL
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql  

  data:
    jdbc:
      repositories:
        enabled: true
    